ALTER TABLE public.site_settings
ADD COLUMN IF NOT EXISTS quienes_somos_desc1 TEXT,
ADD COLUMN IF NOT EXISTS quienes_somos_desc2 TEXT,
ADD COLUMN IF NOT EXISTS por_que_desc1 TEXT,
ADD COLUMN IF NOT EXISTS por_que_desc2 TEXT,
ADD COLUMN IF NOT EXISTS para_que_desc1 TEXT,
ADD COLUMN IF NOT EXISTS para_que_desc2 TEXT;
